### ISSUE TITLE
Cannot convert mbtiles after tile-join

### ISSUE THREAD

**Issue by bludash** [akhenakh/kvtiles#4]
Tested on fresh Ubuntu:

1. Generated some tiles with Openmaptile's quickstart (https://github.com/openmaptiles/openmaptiles/blob/master/QUICKSTART.md).

2. Then joined them with Tippecanoe's tile-join:
tile-join --output=combined.mbtiles --force --no-tile-size-limit --no-tile-compression *.mbtiles

3. Converting to kv format via mbtilestokv:
mbtilestokv -centerLat=48.8 -centerLng=2.2 -dbPath="combined.db" -logLevel="INFO" -maxZoom=14 -tilesPath="combined.mbtiles"

Return error message:
{"app":"mbtilestokv","caller":"main.go:41","level":"info","msg":"starting converting tiles","ts":"2021-02-13T22:13:27.574596989Z","version":"no version from LDFLAGS"}
{"app":"mbtilestokv","caller":"main.go:59","error":"can't read data from mbtiles sqlite: no such table: map","level":"error","msg":"can't store tiles in db","ts":"2021-02-13T22:13:27.600890914Z"}

What is wrong? Did I misunderstand something?

Additonal info:
If I have a look at "combined.mbtiles" I see no "map" table:
![sqlite](https://user-images.githubusercontent.com/21332205/107863312-b3093c80-6e53-11eb-8ad9-8f7b0c7cf119.PNG)

**Comment by akhenakh** [comment]
You should have map tables:

```
$ sqlite3 /opt/data/public_files/oceania12.mbtiles                                                                                                                                                             
SQLite version 3.34.1 2021-01-20 14:10:07
Enter ".help" for usage hints.
sqlite> .tables
geocoder_data  grid_key       grids          keymap         metadata
grid_data      grid_utfgrid   images         map            tiles

sqlite> .schema map
CREATE TABLE map (
   zoom_level INTEGER,
   tile_column INTEGER,
   tile_row INTEGER,
   tile_id TEXT,
   grid_id TEXT
);
```

I'm also using tile-join for planet:
tile-join --maximum-zoom=12 -o planet12.mbtiles africa12.mbtiles asia12.mbtiles oceania12.mbtiles europa12.mbtiles north-america12.mbtiles south-america12.mbtiles central-america12.mbtiles antarctica12.mbtiles

**Comment by bludash** [comment]
Ok now I tried "tile-join" with parameter  "--maximum-zoom=14" as you did. But same result. There is no "map" table inside the created combine.mbtiles.

tile-join uses mapbox/tippecanoe/mbtiles.cpp.
I can only find the SQL insert "insert into tiles (zoom_level, tile_column, tile_row, tile_data) values (?, ?, ?, ?)";

And this states the table "tiles" not "map". 

Am I using the wrong tile-join?

**Comment by akhenakh** [comment]
Can you try on a mbtiles produced by openmaptiles directly ?

**Comment by bludash** [comment]
The tiles rendered with Openmaptile's quickstart work flawlessly.

**Comment by akhenakh** [comment]
The truth is you don’t need tile-join first, you can use multiple mbtiles, just invoke mbtilestokv several times with the same output.

**Comment by bludash** [comment]
I didn't konw that.
But when I do this:
"./cmd/mbtilestokv/mbtilestokv -dbPath="combined.db" -maxZoom=14 -tilesPath="belgium.mbtiles"
followed by 
"./cmd/mbtilestokv/mbtilestokv -dbPath="combined.db" -maxZoom=14 -tilesPath="netherlands.mbtiles"

I get a map where one tile seems to overwrite the data from the other one:
![belgium-netherland-z14](https://user-images.githubusercontent.com/21332205/108116728-5056b180-709c-11eb-80cd-e3f7f61259c8.jpg)

Live map:
https://circles.blufoo.com/map.php#7.17/51.163/4.623

**Comment by bludash** [comment]
Are there any news on this issue? Can I somehow help to resolve it?

**Comment by akhenakh** [comment]
This is a produced openmaptiles:
```
CREATE TABLE map (
   zoom_level INTEGER,
   tile_column INTEGER,
   tile_row INTEGER,
   tile_id TEXT,
   grid_id TEXT
);
CREATE UNIQUE INDEX map_index ON map (zoom_level, tile_column, tile_row);
CREATE INDEX map_grid_id ON map (grid_id);

CREATE VIEW tiles AS
    SELECT
        map.zoom_level AS zoom_level,
        map.tile_column AS tile_column,
        map.tile_row AS tile_row,
        images.tile_data AS tile_data
    FROM map
    JOIN images ON images.tile_id = map.tile_id
```

But the mbtiles spec says the table is tiles.

https://github.com/mapbox/mbtiles-spec/blob/master/1.3/spec.md#tiles

**Comment by akhenakh** [comment]
Sql needs to be rewritten to use the mbtiles spec rather than openmaptiles

**Comment by bludash** [comment]
My aim is to serve the whole planet (zoom = 14) with kvtiles. I rendered all countries or similar big parts) with Openmaptiles Quickstart sucessfully. Now I have all the mbtiles here waiting to get joined by tile-join and converted by mbtilestokv and served by kvtiles.

You wrote that you use tile-join to join the whole planet at zoom level 12. Can you run mbtilestokv on it?
I suppose not, because the "map" table isn't generated by join-tiles.

What do you mean with "Sql needs to be rewritten to use the mbtiles spec rather than openmaptiles"?
Rewrite Sql commands inside mbtilestokv?

Now I tried this:

1. Join country tiles with tile-join. This results in a file with:
CREATE TABLE tiles (zoom_level integer, tile_column integer, tile_row integer, tile_data blob)

2. Create two Sql views to simulate the mbtilestokv-required format:
CREATE VIEW map AS
    SELECT
        tiles.zoom_level AS zoom_level,
        tiles.tile_column AS tile_column,
        tiles.tile_row AS tile_row,
        tiles.zoom_level || '.' || tiles.tile_column || '.' || tiles.tile_row AS tile_id
    FROM tiles

CREATE VIEW images AS
    SELECT
        tiles.tile_data AS tile_data,
        tiles.zoom_level || '.' || tiles.tile_column || '.' || tiles.tile_row AS tile_id
    FROM tiles
   
3. Convert via mbtilestokv

4. Server resulting file with kvtilesd. But: Map is empty.

Would you suggest another workflow?

**Comment by bludash** [comment]
Is here anybody serving the whole planet with kvtiles at zoom 14?

Or what other servers do you recommend?

**Comment by akhenakh** [comment]
closing since kvtiles use a new method, to answer your question kvtiles can work with something as low as a rpi, it's doing only basic ios.
